devise_example-master/config/routes.rb
DeviseExample::Application.routes.draw do




  devise_for :users, :admins


  get '/token' => 'home#token', as: :token
  post 'games/add_level'
  post 'games/remove_level'
  post 'games/save_scores'
  get '/stats/topofday', as: :stats

  resources :home, only: :index
  resources :admins, only: :index
  resources :levels
  resources :games
  #resources :stats

  root 'home#index'

end

devise_example-master/app/models/admin.rb
class Admin < ActiveRecord::Base

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

devise_example-master/app/models/game.rb
class Game < ActiveRecord::Base
  has_many :levels
  belongs_to :user

  accepts_nested_attributes_for :levels
end

devise_example-master/app/models/level.rb
class Level < ActiveRecord::Base
  belongs_to :game#, ->{ includes :user_id }
  belongs_to :user
end

devise_example-master/app/models/user.rb
class User < ActiveRecord::Base
  has_many :games
  has_many :levels, :through=> :games

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :token_authenticatable, :confirmable, :lockable




end

devise_example-master/app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :authenticate_admin!

end

devise_example-master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit! }
  end

end

devise_example-master/app/controllers/games_controller.rb
class GamesController < ApplicationController

  before_action :set_game,:initialize, only: [:show, :edit, :update, :destroy]

  attr_reader :levels


  def initialize
    if @game
      @levels = [] unless @levels
      get_levels
    end

  end


  def add_level
    set_game
    @level = @game.levels.create(:game_id=>params[:id])
    @level.save
    flash[:notice]="Level added"

    redirect_to edit_game_path(params[:id])

  end

  def remove_level
      set_game
      unless @game.levels.length < 2
        get_levels
        @level=@levels.pop
        @level.destroy
        flash[:notice]="Removed Level"
      else
        flash[:notice]="Cannot remove last Level"

      end
      redirect_to edit_game_path(params[:id])


  end

  def save_scores
    #Save all scores from fields in editview


     redirect_to edit_game_path(params[:id])

  end

  # GET /games
  # GET /games.json
  def index
    @games = Game.where(:user_id=> current_user.id)
    render layout: 'application'

  end

  # GET /games/1
  # GET /games/1.json
  def show
    get_levels
    respond_to do |format|
        format.html { redirect_to games_url(params[:id]) }
        format.json { render json: @levels}

    end

  end

  # GET /games/new
  def new
    @game = Game.new
    @game.user_id = current_user.id
    @game.save
    @level = @game.levels.create(:game_id=>@game)
    @level.save
    render layout: 'application'

  end


  # GET /games/1/edit
  def edit
    render layout: 'application'

  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render action: 'show', status: :created, location: @game }
      else
        format.html { render action: 'new' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end

  private
  #levels for game
  def get_levels
    @levels =  Level.where(:game_id=>@game)
  end

    # Use callbacks to share common setup or constraints between actions.
    def set_game
        @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:name, levels_attributes: [:score, :id])
    end
end

devise_example-master/app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_action :authenticate_user!, only: :token

  def token
    render layout: 'application'

  end

  def initialize
    unless @game
      get_games

      #@levels = [] unless @levels
      #get_levels
    end

  end

  def index
    render layout: 'application'

  end



  def get_levels
    @levels =  Level.where(:game_id=>@game)
  end

  # Use callbacks to share common setup or constraints between actions.
  def get_games
    @games = Game.where(:user_id=>:id)
  end

end

devise_example-master/app/controllers/stats_controller.rb
class StatsController < ApplicationController
  def topofday
    set_game
    get_levels
  end

  def get_levels
    @levels =  Level.where(:game_id=>@games)
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_game
    @games = Game.where('created_at BETWEEN ? AND ?', DateTime.now.beginning_of_day, DateTime.now.end_of_day).all
  end

  def sum_game

    #For each user_id, sum levels


  end
end

devise_example-master/app/helpers/application_helper.rb
module ApplicationHelper
end

devise_example-master/app/helpers/games_helper.rb
module GamesHelper
end

devise_example-master/app/helpers/layout_helper.rb
module LayoutHelper
  def title(page_title, show_title = true)
    @content_for_title = page_title.to_s
    @show_title = show_title
  end

  def show_title?
    @show_title
  end
end

devise_example-master/app/helpers/stats_helper.rb
module StatsHelper
end

devise_example-master/app/views/admins/index.html.erb
<% title 'Admin' -%>

<p>Welcome to Admin Section.</p>

devise_example-master/app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

devise_example-master/app/views/games/_level_form.html.erb
<p>Found : <%= @levels.length%> levels.</p>
<h2>Score board:</h2>
<% @levels.each do |level|%>
    <%= form_for(level) do |f| %>
        <% if level.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(level.errors.count, "error") %> prohibited this level from being saved:</h2>

              <ul>
                <% level.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

        <div class="field">
          <%= f.text_field :score %>
        </div>
        <div class="actions">
          <!--<%= f.submit %>    -->
        </div>
    <% end %>

<%end%>
<%= button_to "Store Scores",
              :action => 'save_scores',
              :id =>@game
%>

devise_example-master/app/views/games/_list.html.erb
<p>Found : <%= @levels.length%> levels.</p>
<% @levels.each do |level|%>
 <p><%= level%> </p>
<%end%>

devise_example-master/app/views/games/edit.html.erb
<h1>Editing game</h1>

<% flash.each do |name, msg| -%>
    <%= content_tag :div, msg, class: name %>
<% end -%>


<!--START-->
<%= form_for @game do |f| %>
    <h3>Label:</h3>
   <!-- <%= f.label :name %> --><%= f.text_field :name %>
    <h3>Scores:</h3>

    <%= f.fields_for(:levels) do |level_form| %>
        <!--<%= level_form.label :score %>-->
        <%= level_form.text_field :score %>
        </br>
    <% end %>

    <%= f.submit "Store Result"%>
<% end %>
           <!--END-->

<p><div style="float: left; width: auto;">
<%= button_to "Add Level",
              :action => 'add_level',
              :id =>@game
              %></div>
<%= button_to "Remove Level",
              :action => 'remove_level',
              :id =>@game
%> </p>

<!--<%= link_to 'Show', @game %>-->
<%= link_to 'Back', games_path %>

devise_example-master/app/views/games/index.html.erb
<% unless user_signed_in? -%>
    <p><%= link_to 'Sign up as User', new_user_registration_path %></p>
    <p><%= link_to 'Sign in as User', new_user_session_path %></p>
<% end -%>
<% if user_signed_in? -%>

<h1>Listing games</h1>

<table>
  <thead>
    <tr>
      <th>Games:</th>
      <th>Played at:</th>
      <th>Actions:</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.name %></td>
        <td><%= game.created_at.to_formatted_s(:short) %></td>

        <!--<td><%= button_to "Show", (game), :class => "button", :method => :get %></td>     -->
        <td><%= button_to "Show", edit_game_path(game), :class => "button", :method => :get %></td>
        <td><%= button_to "Delete", game, :method=>:delete, :class=>:destroy, :confirm => 'Are you sure?'%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>
 <%end%>

devise_example-master/app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

devise_example-master/app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>List:</strong>
  <%= @game.name %>
  <%= render 'list'%>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

devise_example-master/app/views/home/_list.html.erb
<p>Found : <%= @games.length%> games.</p>
<% @games.each do |game|%>
    <p><%= game%> </p>
<%end%>

devise_example-master/app/views/home/index.html.erb
<h1>Welcome To </br>Disc Golf Manager</h1>

<!----><% unless admin_signed_in? -%>
  <p><%= link_to 'Sign up as Admin', new_admin_registration_path %></p>
  <p><%= link_to 'Sign in as Admin', new_admin_session_path %></p>
<% end -%>  <!---->

<% unless user_signed_in? -%>
  <p><%= link_to 'Sign up as User', new_user_registration_path %></p>
  <p><%= link_to 'Sign in as User', new_user_session_path %></p>
<% end -%>

<% if user_signed_in? -%>
  <p><%= link_to 'Token Authentication Example', token_path(auth_token: current_user.authentication_token) %></p>
  <%= link_to 'Games', games_path %>
    <%= link_to 'Scores', stats_path%>
    <p>Hello!</p>
    <p><%= current_user.email %> </p>
    <p>Last sign in:<%=current_user.last_sign_in_at %> </p>

<% end -%>

devise_example-master/app/views/home/token.html.erb
<h1>Hello, <%= current_user.email %></h1>

<p>This link (with the auth_token param) will work even if you're not signed in.</p>

<p>Save this link, sign out, and try it!</p>

devise_example-master/app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title><%= h(yield(:title) || "Devise") %></title>
    <%= csrf_meta_tag %>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag :application %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <%- flash.each do |name, msg| -%>
        <%= content_tag :div, msg, id: "flash_#{name}" if msg.is_a?(String) %>
      <%- end -%>

      <p><%= link_to 'Home', root_path %></p>

      <% if user_signed_in? -%>
        <div id="user_login_box" style="float:right">
          <%= current_user.email %> |
          <%= link_to 'My info', edit_user_registration_path %> |
          <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
        </div>
      <% end -%>
      <% if admin_signed_in? -%>
        <div id="admin_login_box" style="float:left">
          <%= current_admin.email %> |
          <%= link_to 'Admin section', admins_path %> |
          <%= link_to 'Sign out', destroy_admin_session_path, method: :delete %>
        </div>
      <% end -%>
      <div style="clear:both"></div>

      <%- if show_title? -%>
        <h1><%=h yield(:title) %></h1>
      <%- end -%>

      <%= yield %>
    </div>
  </body>
</html>

devise_example-master/app/views/stats/topofday.html.erb
<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
<h1>Scores:</h1>

<h2>Your Games:</h2>
<%= column_chart Level.group(:game_id).sum(:score) %>

<h2>Everyones Games:</h2>
<h3>Games Played:</h3>
<%= line_chart Game.group_by_day(:created_at).count, :id => "users-chart", :height => "500px" %>

<h3>High Score:</h3>
<%= column_chart User.includes(:levels).group(:email).sum(:score) %>

<h3>Average Score per Player aquired each game:</h3>
<%= column_chart User.includes(:levels).group(:email, :game_id).average(:score) %>

<h3>New Users :</h3>
<%= line_chart User.group_by_day(:created_at).count %>